---
package_groups:
  desktop:
    - name: cosmic
      arch:
        repo:
          - cosmic-applets
          - cosmic-app-library
          - cosmic-bg
          - cosmic-comp
          - cosmic-files
          - cosmic-greeter
          - cosmic-icon-theme
          - cosmic-idle
          - cosmic-launcher
          - cosmic-notifications
          - cosmic-osd
          - cosmic-panel
          - cosmic-player
          - cosmic-randr
          - cosmic-screenshot
          - cosmic-session
          - cosmic-settings
          - cosmic-settings-daemon
          - cosmic-terminal
          - cosmic-text-editor
          - cosmic-wallpapers
          - cosmic-workspaces
          - xdg-desktop-portal-cosmic

  browser:
    - name: floorp
      arch:
        aur: [ floorp-bin ]

  chat:
    - name: vesktop
      arch:
        aur: [ vesktop ]

  voip:
    - name: teamspeak3
      arch: { repo: [ teamspeak3 ] }

  gaming:
    - name: steam
      arch: { repo: [ steam ] }
    - name: faugus-launcher
      arch:
        aur: [ faugus-launcher ]

  development:
    - name: intellij-idea
      arch: { repo: [ intellij-idea-community-edition ] }

  shell:
    - name: fish
      arch: { repo: [ fish, fastfetch, eza, bat ] }